---
title: RAPPORT TECHNIQUE
subtitle: Moteur Morphologique Arabe
author:
  - Arij Sebai
  - Hadil Hasni
  - Balkis Hanafi
date: 2025-2026
geometry:
  - margin=2cm
  - top=2.5cm
  - bottom=2.5cm
fontsize: 12pt
papersize: a4
colorlinks: true
urlcolor: blue
linkcolor: blue
toc: false
lang: fr-FR
---
